<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'LAST NEWS' => 'SO`NGGI YANGILIKALAR',
    'Developed by' => 'Разработан в <a href="{url}">PROACTIVE MEDIA</a>',
    'SHARE:' => 'ULASHISH:',
    'Please confirm that you are not a bot.' => 'Iltimos, bot emasligingizni tasdiqlang.',
    'Enter your name here.' => 'Ismingizni shu yerga kiriting.',
    'Enter your phone or email here.' => 'Telefoningiz yoki emailingizni shu erga kiriting .',
    'Enter your message here.' => 'Xabaringizni shu erga kiriting ..',
    'Submit' => 'Yuborish',
    'Contact us' => 'Biz bilan bog`laning',
    'Other' => 'Boshqa',
    'Subscribe' => 'Obuna bo\'ling',
    'Previous' => 'Oldingi',
    'Next' => 'Keyingi',
    'All' => 'Barchasi',
    'Articles' => 'Maqolalar',
    'Videos' => 'Videolar',
    'Audio' => 'Audio',
    'Books' => 'Kitoblar',
    'News' => 'Yangiliklar',
    'It was 01:41:33 before dawn' => 'Azongacha 01:41:33 qoldi',
    'Special facilities' => 'Maxsus imkoniyatlar',
    'Font size:' => 'Shrift o\'lchami:',
    'Radio' => 'Radio',
    'TV' => 'TV',
    'Fajr' => 'Bomdod',
    'Sunrise' => 'Quyosh',
    'Dhuhr' => 'Peshin',
    'Asr' => 'Asr',
    'Maghrib' => 'Shom',
    'Isha' => 'Xufton',
    'The site is working in test mode!' => 'Sayt test holatida ishlamoqda!',
    'If you think this is a server error, please contact us. Thank you.' => 'Agar bu server xatosi deb hisoblasangiz, iltimos, biz bilan bog\'laning. Rahmat.',
    'Contact Information' => 'Bog\'lanish uchun ma\'lumot',
    'Page Not Found' => 'Sahifa topilmadi',
    'Author\'s articles' => 'Muallif maqolalari',
    'Regions' => 'Hududlar',
    'Iman' => 'Iymon',
    'Prayer' => 'Namoz',
    'Fasting'=> 'Ro\'za',
    'Zakat' => 'Zakot',
    'Haj' => 'Haj',
    'Contact' => 'Aloqa',
    'Search' => 'Qidirish',
    'There are <span id="{days}"></span> left until dawn' => 'Azongacha <span id="{days}"></span> qoldi',
    'SHARE INFORMATION ON SOCIAL NETWORKS' => 'MАЪLUMOTNI IJTIMOIY TАRMOQLАRDА ULАShING',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Biz bilan bog\'langaningiz uchun tashakkur. Biz sizga imkon qadar tezroq javob beramiz.',
    'Name' => 'Nomi',
    'Email or phone' => 'Email yoki telefon raqam',
    'Message' => 'Xabar',
    'Lessons' => 'Darslar',
    'Qur`an' => 'Qur\'on',
    '{attribute} cannot be blank.' => '«{attribute}» bo\'sh bo\'lishi mumkin emas.',
    'Monday' => 'Dushanba',
    'Tuesday' => 'Seshanba',
    'Wednesday' => 'Chorshanba',
    'Thursday' => 'Payshanba',
    'Friday' => 'Juma',
    'Saturday' => 'Shanba',
    'Sunday' => 'Yakshanba',





];
