<?php

namespace backend\models;

use himiklab\yii2\recaptcha\ReCaptchaValidator2;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\helpers\Html;

/**
 * This is the model class for table "contacts".
 *
 * @property integer $id
 * @property integer $status
 * @property string $full_name
 * @property string $email_phone
 * @property string $message
 * @property int $created_at [int(11) unsigned]
 */
class Contacts extends ActiveRecord
{
    public static function tableName()
    {
        return 'feedback'; 
    }

    public $verifyCode;
    public $reCaptcha;

    public function rules()
    {
        return [
            [['full_name', 'email_phone', 'message'], 'required'],
            [['status'], 'integer'],
            [['status'], 'default', 'value' => 0],
            [['message'], 'string', 'max' => 1000],
            [['full_name', 'email_phone'], 'string', 'max' => 100],
            [['reCaptcha'], ReCaptchaValidator2::class,
                'uncheckedMessage' => Yii::t('app', 'Please confirm that you are not a bot.')
            ],
        ];
    }


    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'full_name' => Yii::t('app', 'Full Name'),
            'email_phone' => Yii::t('app', 'Email or phone'),
            'message' => Yii::t('app', 'Message'),
            'created_at' => Yii::t('app', 'Created At'),
        ];
    }


    public function behaviors()
    {
        return [
            TimestampBehavior::class
        ];
    }


    public function beforeSave($insert)
    {
        $this->full_name = Html::encode($this->full_name);
        $this->email_phone = Html::encode($this->email_phone);
        $this->message = Html::encode($this->message);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
