<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'LAST NEWS' => 'СЎНГГИ ЯНГИЛИКЛAР',
    'Developed by <a href="{url}">PROACTIVE MEDIA</a>' => 'Разработан в <a href="{url}">PROACTIVE MEDIA</a>',
    'SHARE:' => 'ULASHISH:',
    'Please confirm that you are not a bot.' => 'Илтимос, бот емаслигингизни тасдиқланг.',
    'Enter your name here.' => 'Исмингизни шу йерга киритинг.',
    'Enter your phone or email here.' => 'Телефонингиз ёки емаилингизни шу ерга киритинг .',
    'Enter your message here.' => 'Хабарингизни шу ерга киритинг ..',
    'Submit' => 'Юбориш',
    'Contact us' => 'Биз билан боғланинг',
    'Other' => 'Бошқа',
    'Subscribe' => 'Обуна бўлинг',
    'Previous' => 'Олдинги',
    'Next' => 'Кейинги',
    'All' => 'Барчаси',
    'Articles' => 'Мақолалар',
    'Videos' => 'Видеолар',
    'Audio' => 'Aудио',
    'Books' => 'Китоблар',
    'News' => 'Янгиликлар',
    'It was 01:41:33 before dawn' => 'Aзонгача 01:41:33 қолди',
    'Special facilities' => 'Махсус имкониятлар',
    'Font size:' => 'Шрифт ўлчами:',
    'Radio' => 'Радио',
    'TV' => 'ТВ',
    'Fajr' => 'Бомдод',
    'Sunrise' => 'Қуёш',
    'Dhuhr' => 'Пешин',
    'Asr' => 'Аср',
    'Maghrib' => 'Шом',
    'Isha' => 'Хуфтон',
    'The site is working in test mode!' => 'Сайт тест ҳолатида ишламоқда!',
    'If you think this is a server error, please contact us. Thank you.' => 'Aгар бу сервер хатоси деб ҳисобласангиз, илтимос, биз билан боғланинг. Раҳмат.',
    'Contact Information' => 'Боғланиш учун маълумот',
    'Page Not Found' => 'Саҳифа топилмади',
    'Author\'s articles' => 'Муаллиф мақолалари',
    'Regions' => 'Ҳудудлар',
    'Iman' => 'Иймон',
    'Prayer' => 'Намоз',
    'Fasting'=> 'Рўза',
    'Zakat' => 'Закот',
    'Haj' => 'Хадж',
    'Contact' => 'Aлоқа',
    'Search' => 'Қидириш',
    'There are <span id="{days}"></span> left until dawn' => 'Aзонгача <span id="{days}"></span> қолди',
    'SHARE INFORMATION ON SOCIAL NETWORKS' => 'МАЪЛУМОТНИ ИЖТИМОИЙ ТАРМОҚЛАРДА УЛАШИНГ',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Биз билан боғланганингиз учун ташаккур. Биз сизга имкон қадар тезроқ жавоб берамиз.',
    '{attribute} cannot be blank.' => '«{attribute}» тўлдириш шарт.',
    'Name' => 'Номи',
    'Email or phone' => 'Эмаил ёки телефон рақам',
    'Message' => 'Хабар',
    'Lessons' => 'Дарслар',
    'Qur`an' => 'Қуръон',
    'Monday' => 'Душанба',
    'Tuesday' => 'Сешанба',
    'Wednesday' => 'Чоршанба',
    'Thursday' => 'Пайшанба',
    'Friday' => 'Жума',
    'Saturday' => 'Шанба',
    'Sunday' => 'Якшанба',



];
