<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'LAST NEWS' => 'آخر الأخبار',
    'Developed by <a href="{url}">PROACTIVE MEDIA</a>' => 'تم التطوير بواسطة <a href="{url}"> الوسائط الاستباقية </a>',
    'SHARE:' => 'يشارك:',
    'Please confirm that you are not a bot.' => 'يرجى تأكيد أنك لست روبوت.',
    'Enter your name here.' => 'أدخل اسمك هنا.',
    'Enter your phone or email here.' => 'أدخل هاتفك أو بريدك الإلكتروني هنا.',
    'Enter your message here.' => 'أدخل رسالتك هنا.',
    'Submit' => 'إرسال',
    'Contact us' => 'اتصل بنا',
    'Other' => 'آخر',
    'Subscribe' => 'الإشتراك',
    'Previous' => 'سابق',
    'Next' => 'التالي',
    'All' => 'الجميع',
    'Articles' => 'مقالات',
    'Videos' => 'أشرطة فيديو',
    'Audio' => 'صوتي',
    'Books' => 'كتب',
    'News' => 'أخبار',
    'It was 01:41:33 before dawn' => 'كانت الساعة 01:41:33 قبل الفجر',
    'Special facilities' => 'مرافق خاصة',
    'Font size:' => 'حجم الخط:',
    'Radio' => 'مذياع',
    'TV' => 'تلفزيون',
    'Fajr' => 'الفجر',
    'Sunrise' => 'شروق',
    'Dhuhr' => 'الظهر',
    'Asr' => 'العصر',
    'Maghrib' => 'المغرب',
    'Isha' => 'العشاء',
    'The site is working in test mode!' => 'الموقع يعمل في وضع الاختبار!',
    'If you think this is a server error, please contact us. Thank you.' => 'إذا كنت تعتقد أن هذا خطأ في الخادم ، فيرجى الاتصال بنا. شكرا لك.',
    'Contact Information' => 'معلومات للتواصل',
    'Page Not Found' => 'الصفحة غير موجودة',
    'Author\'s articles' => 'مقالات المؤلف',
    'Regions' => 'المناطق',
    'Iman' => 'إيمان',
    'Prayer' => 'دعاء',
    'Fasting'=> 'الصوم',
    'Zakat' => 'زاكوت',
    'Haj' => 'الحج',
    'Contact' => 'زعقوت',
    'Qur\'an' => 'القرآن',
    'Lessons' => 'الدروس',
    'Search' => 'بحث',
    'There are <span id="{days}"></span> left until dawn' => 'حتى الفجر <span id="{days}"></span> بقي',
    'SHARE INFORMATION ON SOCIAL NETWORKS' => 'شارك المعلومات على الشبكات الاجتماعية',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'أشكركم على الاتصال بنا. سوف نرد عليك بأقرب وقت ممكن.',
    'Name' => 'اسم',
    'Email or phone' => 'بريد الكتروني او هاتف',
    'Message' => 'رسالة',
    'Qur`an' => 'القرآن',
    '{attribute} cannot be blank.' => '«{attribute}» لا يمكن أن يكون فارغا.',
    'Monday' => 'الإثنين',
    'Tuesday' => 'يوم الثلاثاء',
    'Wednesday' => 'الأربعاء',
    'Thursday' => 'يوم الخميس',
    'Friday' => 'جمعة',
    'Saturday' => 'السبت',
    'Sunday' => 'يوم الأحد',





];
