<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'LAST NEWS' => 'ПОСЛЕДНИЕ НОВОСТИ',
    'Developed by <a href="{url}">PROACTIVE MEDIA</a>' => 'Разработан в <a href="{url}">PROACTIVE MEDIA</a>',
    'SHARE:' => 'ПОДЕЛИТЬСЯ:',
    'Please confirm that you are not a bot.' => 'Пожалуйста, подтвердите, что вы не бот.',
    'Enter your name here.' => 'Введите ваше имя здесь.',
    'Enter your phone or email here.' => 'Введите здесь свой телефон или адрес электронной почты.',
    'Enter your message here.' => 'Введите свое сообщение здесь.',
    'Submit' => 'Отправить',
    'Contact us' => 'Свяжитесь с нами',
    'Other' => 'Другой',
    'Subscribe' => 'Подписаться',
    'Previous' => 'Предыдущий',
    'Next' => 'Следующий',
    'All' => 'Все',
    'Articles' => 'Статьи',
    'Videos' => 'Видео',
    'Audio' => 'Aудио',
    'Books' => 'Книги',
    'News' => 'Новости',
    'It was 01:41:33 before dawn' => 'До рассвета было 01:41:33',
    'Special facilities' => 'Специальные объекты',
    'Font size:' => 'Размер шрифта:',
    'Radio' => 'Радио',
    'TV' => 'ТВ',
    'Fajr' => 'Фаджр',
    'Sunrise' => 'Шурук',
    'Dhuhr' => 'Зухр',
    'Asr' => 'Аср',
    'Maghrib' => 'Магриб',
    'Isha' => 'Иша',
    'The site is working in test mode!' => 'Сайт работает в тестовом режиме!',
    'If you think this is a server error, please contact us. Thank you.' => 'Если вы считаете, что это ошибка сервера, свяжитесь с нами. Спасибо.',
    'Contact Information' => 'Контакты',
    'Page Not Found' => 'Страница не найдена',
    'Author\'s articles' => 'Авторские статьи',
    'Regions' => 'Регионы',
    'Iman' => 'Иман',
    'Prayer' => 'Молитва',
    'Fasting'=> 'Голодание',
    'Zakat' => 'Закот',
    'Haj' => 'Хадж',
    'Contact' => 'Контакт',
    'Search' => 'Поиск',
    'There are <span id="{days}"></span> left until dawn' => 'Осталось <span id="{days}"></span> до рассвета',
    'SHARE INFORMATION ON SOCIAL NETWORKS' => 'ПОДЕЛИТЬСЯ ИНФОРМАЦИЕЙ В СОЦИАЛЬНЫХ СЕТЯХ',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Благодарим Вас за обращение к нам. Мы ответим вам как можно скорее.',
    'Name' => 'Имя',
    'Email or phone' => 'По электронной почте или телефону',
    'Message' => 'Сообщение',
    'Lessons' => 'Уроки',
    'Qur`an' => 'Коран',
    '{attribute} cannot be blank.' => '«{attribute}» не может быть пустым.',
    'Monday' => 'Понедельник',
    'Tuesday' => 'Вторник',
    'Wednesday' => 'Среда',
    'Thursday' => 'Четверг',
    'Friday' => 'Пятница',
    'Saturday' => 'Суббота',
    'Sunday' => 'Воскресенье',








];
